import type { SupabaseClient } from '@supabase/supabase-js'
import { ALLOWED_EXTENSIONS,ALLOWED_MIME_TYPES,MAX_FILE_SIZE } from '@/lib/gmail-attachments'
import type { Incoming,IncomingAttachment } from './incoming'
import type { MailProvider } from './security'

const MAX_FILES=5,MAX_TOTAL=20*1024*1024
const safe=(name:string)=>name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-180)||'bilaga'
const allowed=(a:IncomingAttachment)=>!!ALLOWED_MIME_TYPES[a.mimeType]||ALLOWED_EXTENSIONS.has(a.name.split('.').pop()?.toLowerCase()||'')
async function fetchBytes(provider:MailProvider,token:string,messageId:string,a:IncomingAttachment){const url=provider==='google'?`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(messageId)}/attachments/${encodeURIComponent(a.id)}`:`https://graph.microsoft.com/v1.0/me/messages/${encodeURIComponent(messageId)}/attachments/${encodeURIComponent(a.id)}/$value`;const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,...(provider==='microsoft'?{Prefer:'IdType="ImmutableId"'}:{})},signal:AbortSignal.timeout(20000),redirect:'error',cache:'no-store'});if(!r.ok)throw new Error(`Bilagan ${a.name} kunde inte hämtas.`);if(provider==='google'){const body=await r.json();if(typeof body.data!=='string')throw new Error(`Bilagan ${a.name} saknade innehåll.`);return Buffer.from(body.data,'base64url')}return Buffer.from(await r.arrayBuffer())}
async function microsoftList(token:string,messageId:string){const u=`https://graph.microsoft.com/v1.0/me/messages/${encodeURIComponent(messageId)}/attachments?$select=id,name,contentType,size,isInline`;const r=await fetch(u,{headers:{Authorization:`Bearer ${token}`,Prefer:'IdType="ImmutableId"'},signal:AbortSignal.timeout(12000),redirect:'error',cache:'no-store'});if(!r.ok)throw new Error('Outlook-bilagorna kunde inte läsas.');const b=await r.json();if(!Array.isArray(b.value))throw new Error('Outlook lämnade en ogiltig bilagelista.');return b.value.filter((v:any)=>v['@odata.type']==='#microsoft.graph.fileAttachment'&&!v.isInline).map((v:any)=>({id:String(v.id),name:String(v.name||'bilaga'),mimeType:String(v.contentType||'application/octet-stream'),size:Number(v.size)||0})) as IncomingAttachment[]}
export async function saveDirectAttachments(db:SupabaseClient,input:{provider:MailProvider;token:string;businessId:string;message:Incoming;customerId:string|null;leadId:string|null}){let files=input.provider==='microsoft'&&input.message.hasAttachments?await microsoftList(input.token,input.message.messageId):(input.message.attachments||[]);let skipped=0,total=0;files=files.filter(a=>{if(!allowed(a)||a.size>MAX_FILE_SIZE||total+a.size>MAX_TOTAL){skipped++;return false}total+=a.size;return true});if(files.length>MAX_FILES){skipped+=files.length-MAX_FILES;files=files.slice(0,MAX_FILES)}let saved=0;for(const a of files){const path=`${input.businessId}/mail/${input.provider}/${encodeURIComponent(input.message.messageId)}/${safe(a.name)}`;const existing=await db.from('customer_document').select('id').eq('business_id',input.businessId).eq('storage_path',path).maybeSingle();if(existing.error)throw new Error(`Bilagan ${a.name} kunde inte kontrolleras.`);if(existing.data){saved++;continue}const bytes=await fetchBytes(input.provider,input.token,input.message.messageId,a);if(bytes.length>MAX_FILE_SIZE)throw new Error(`Bilagan ${a.name} överskred storleksgränsen.`);const contentType=ALLOWED_MIME_TYPES[a.mimeType]?a.mimeType:'application/octet-stream';const upload=await db.storage.from('customer-documents').upload(path,bytes,{contentType,upsert:false});if(upload.error)throw new Error(`Bilagan ${a.name} kunde inte lagras.`);const row=await db.from('customer_document').insert({customer_id:input.customerId,business_id:input.businessId,file_name:a.name,file_url:path,file_type:contentType,file_size:bytes.length,category:'lead_attachment',source:`${input.provider}_mail`,lead_id:input.leadId,storage_path:path}).select('id').single();if(row.error||!row.data){await db.storage.from('customer-documents').remove([path]);throw new Error(`Bilagan ${a.name} kunde inte registreras.`)}saved++}return{saved,skipped}}
