import { createRemoteJWKSet,jwtVerify } from 'jose'
import { config,digest,type MailProvider } from './security'
const googleKeys=createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs'))
const microsoftKeys=createRemoteJWKSet(new URL('https://login.microsoftonline.com/common/discovery/v2.0/keys'))
export class ProviderError extends Error{constructor(readonly status:number,readonly retryAfter=60){super(status===401||status===403?'Anslut mejlkontot igen och kontrollera behörigheten.':'Mejlleverantören kunde inte slutföra anropet.') }}
export async function json(url:string,init:RequestInit={}){const r=await fetch(url,{...init,signal:AbortSignal.timeout(12000),redirect:'error',cache:'no-store'});if(!r.ok)throw new ProviderError(r.status,Math.min(3600,Math.max(30,Number(r.headers.get('retry-after'))||60)));return r.json()}
export function authUrl(provider:MailProvider,state:string,verifier:string,nonce:string){const c=config(provider);if(!c.enabled)throw new Error('Mejlleverantören är inte aktiverad ännu.');const u=new URL(provider==='google'?'https://accounts.google.com/o/oauth2/v2/auth':'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize');u.search=new URLSearchParams({client_id:c.clientId,redirect_uri:c.redirectUri,response_type:'code',scope:provider==='google'?'openid email https://www.googleapis.com/auth/gmail.readonly':'openid profile email offline_access User.Read Mail.Read',state,nonce,code_challenge:digest(verifier),code_challenge_method:'S256',prompt:'consent',...(provider==='google'?{access_type:'offline'}:{})}).toString();return u.toString()}
const tokenUrl=(p:MailProvider)=>p==='google'?'https://oauth2.googleapis.com/token':'https://login.microsoftonline.com/organizations/oauth2/v2.0/token'
export async function exchange(provider:MailProvider,code:string,verifier:string,nonce:string){const c=config(provider),t=await json(tokenUrl(provider),{method:'POST',body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:c.redirectUri,code,code_verifier:verifier,grant_type:'authorization_code'})});if(!t.id_token||!t.access_token||!t.refresh_token)throw new Error('Kontot lämnade inte en förnybar mejlbehörighet.');const{payload}=await jwtVerify(t.id_token,provider==='google'?googleKeys:microsoftKeys,{audience:c.clientId,algorithms:['RS256'],...(provider==='google'?{issuer:['https://accounts.google.com','accounts.google.com']}:{})});if(payload.nonce!==nonce||!payload.sub)throw new Error('Mejlkontots identitet kunde inte verifieras.');let subject='',email='';if(provider==='google'){if(payload.email_verified!==true||typeof payload.email!=='string')throw new Error('Google-adressen är inte verifierad.');subject=payload.sub;email=payload.email;const me=await json('https://gmail.googleapis.com/gmail/v1/users/me/profile',{headers:{Authorization:`Bearer ${t.access_token}`}});if(me.emailAddress?.toLowerCase()!==email.toLowerCase())throw new Error('Google-kontona matchar inte.')}else{const tid=String(payload.tid||'');if(!/^[0-9a-f-]{36}$/i.test(tid)||payload.iss!==`https://login.microsoftonline.com/${tid}/v2.0`||typeof payload.oid!=='string')throw new Error('Microsofts företagskonto kunde inte verifieras.');const me=await json('https://graph.microsoft.com/v1.0/me?$select=id,mail,userPrincipalName',{headers:{Authorization:`Bearer ${t.access_token}`}});if(me.id!==payload.oid)throw new Error('Microsoft-kontona matchar inte.');subject=`${tid}:${payload.oid}`;email=me.mail||me.userPrincipalName}const scopes=String(t.scope||'').split(/\s+/);const read=provider==='google'?'https://www.googleapis.com/auth/gmail.readonly':'Mail.Read';if(!scopes.some((v:string)=>v===read||v===`https://graph.microsoft.com/${read}`))throw new Error('Behörigheten att läsa mejl saknas.');if(!email?.includes('@'))throw new Error('Kontots e-postadress saknas.');return{subject,email:email.toLowerCase(),access_token:String(t.access_token),refresh_token:String(t.refresh_token),expires_at:new Date(Date.now()+(Number(t.expires_in)||3600)*1000).toISOString()}}
export async function refresh(provider:MailProvider,refreshToken:string){const c=config(provider),t=await json(tokenUrl(provider),{method:'POST',body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:refreshToken,grant_type:'refresh_token'})});if(!t.access_token)throw new Error('Mejlinloggningen kunde inte förnyas.');return{access_token:String(t.access_token),refresh_token:String(t.refresh_token||refreshToken),expires_at:new Date(Date.now()+(Number(t.expires_in)||3600)*1000).toISOString()}}
export async function revoke(provider:MailProvider,refreshToken:string){if(provider!=='google')return false;const r=await fetch('https://oauth2.googleapis.com/revoke',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:refreshToken}),signal:AbortSignal.timeout(12000),redirect:'error',cache:'no-store'});return r.ok}
