-- First batch only: synthetic acknowledgement cards, NOT full producer fixtures.
-- Does not certify any type. Idempotent; never resets previously resolved cards.
BEGIN;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM business_config WHERE business_id='biz_rollprov_a' AND business_name='TEST Rollprov A') THEN RAISE EXCEPTION 'Expected test company missing'; END IF;
END $$;
INSERT INTO pending_approvals (id,business_id,approval_type,title,description,payload,status,risk_level,routing_role)
SELECT v.id,v.business_id,v.approval_type,v.title,v.description,v.payload::jsonb,v.status,v.risk_level,v.routing_role FROM (VALUES
('aplive_20260908_karin_deadline','biz_rollprov_a','karin_deadline','[KORTPROV] karin_deadline','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_cert_expiry_reminder','biz_rollprov_a','cert_expiry_reminder','[KORTPROV] cert_expiry_reminder','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_low_stock_alert','biz_rollprov_a','low_stock_alert','[KORTPROV] low_stock_alert','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_agent_insight','biz_rollprov_a','agent_insight','[KORTPROV] agent_insight','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_monthly_review','biz_rollprov_a','monthly_review','[KORTPROV] monthly_review','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_monday_brief','biz_rollprov_a','monday_brief','[KORTPROV] monday_brief','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_quote_signed','biz_rollprov_a','quote_signed','[KORTPROV] quote_signed','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_ata_signed_notification','biz_rollprov_a','ata_signed_notification','[KORTPROV] ata_signed_notification','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_ata_declined_notification','biz_rollprov_a','ata_declined_notification','[KORTPROV] ata_declined_notification','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_profitability_warning','biz_rollprov_a','profitability_warning','[KORTPROV] profitability_warning','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_meeting_summary','biz_rollprov_a','meeting_summary','[KORTPROV] meeting_summary','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_autonomy_revoked','biz_rollprov_a','autonomy_revoked','[KORTPROV] autonomy_revoked','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_team_intro','biz_rollprov_a','team_intro','[KORTPROV] team_intro','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_expectation_drift_signal','biz_rollprov_a','expectation_drift_signal','[KORTPROV] expectation_drift_signal','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_promise_deadline_signal','biz_rollprov_a','promise_deadline_signal','[KORTPROV] promise_deadline_signal','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_mandate_paused_signal','biz_rollprov_a','mandate_paused_signal','[KORTPROV] mandate_paused_signal','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_external_delivery_failure_signal','biz_rollprov_a','external_delivery_failure_signal','[KORTPROV] external_delivery_failure_signal','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_payment_failed_signal','biz_rollprov_a','payment_failed_signal','[KORTPROV] payment_failed_signal','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text),
('aplive_20260908_kort_gar_ut','biz_rollprov_a','kort_gar_ut','[KORTPROV] kort_gar_ut','Syntetiskt prov av läskvittens. Kontrollera korrekt knapp, borttagning ur kö och ärlig historikkvittens.','{"test_run": "approval-live-20260908", "fixture_kind": "synthetic_acknowledgement", "summary": "Syntetiskt läskvittensprov. Ingen verklig händelse, skyldighet eller kundhandling.", "expected_effect": "Endast registrera läst/noterad; inget utskick eller ändring av underlag."}','pending','low','owner'::text)
) AS v(id,business_id,approval_type,title,description,payload,status,risk_level,routing_role)
ON CONFLICT (id) DO NOTHING;
COMMIT;
