-- Snapshot of public schema from pktaqedooyzgvzwipslu, 2026-09-08. No data or secrets.
-- Apply ONLY to isolated test branch eoodwyfxrdjmlqaealhj in numbered order.
SET search_path = public, extensions;
SET check_function_bodies = false;
CREATE INDEX idx_customer_phone ON public.customer USING btree (phone_number);
CREATE INDEX idx_customer_business ON public.customer USING btree (business_id);
CREATE INDEX idx_customer_postal ON public.customer USING btree (postal_code);
CREATE INDEX idx_call_business ON public.call USING btree (business_id);
CREATE INDEX idx_call_customer ON public.call USING btree (customer_id);
CREATE INDEX idx_call_started ON public.call USING btree (started_at);
CREATE INDEX idx_call_vapi ON public.call USING btree (vapi_call_id);
CREATE INDEX idx_case_business ON public.case_record USING btree (business_id);
CREATE INDEX idx_case_customer ON public.case_record USING btree (customer_id);
CREATE INDEX idx_case_status ON public.case_record USING btree (status);
CREATE INDEX idx_case_created ON public.case_record USING btree (created_at);
CREATE INDEX idx_reservation_business ON public.reservation USING btree (business_id);
CREATE INDEX idx_reservation_case ON public.reservation USING btree (case_id);
CREATE INDEX idx_reservation_slot ON public.reservation USING btree (slot_id);
CREATE INDEX idx_reservation_status ON public.reservation USING btree (status) WHERE (status = 'held'::reservation_status);
CREATE INDEX idx_reservation_expires ON public.reservation USING btree (expires_at) WHERE (status = 'held'::reservation_status);
CREATE UNIQUE INDEX idx_reservation_active_slot ON public.reservation USING btree (business_id, slot_id) WHERE (status = 'held'::reservation_status);
CREATE UNIQUE INDEX idx_reservation_idempotency ON public.reservation USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX idx_booking_business ON public.booking USING btree (business_id);
CREATE INDEX idx_booking_customer ON public.booking USING btree (customer_id);
CREATE INDEX idx_booking_case ON public.booking USING btree (case_id);
CREATE INDEX idx_booking_scheduled ON public.booking USING btree (scheduled_start);
CREATE INDEX idx_booking_status ON public.booking USING btree (status);
CREATE UNIQUE INDEX idx_booking_slot ON public.booking USING btree (business_id, slot_id) WHERE (status = 'confirmed'::booking_status);
CREATE UNIQUE INDEX idx_booking_idempotency ON public.booking USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX idx_queue_business ON public.human_followup_queue USING btree (business_id);
CREATE INDEX idx_queue_case ON public.human_followup_queue USING btree (case_id);
CREATE INDEX idx_queue_pending ON public.human_followup_queue USING btree (business_id, priority, queued_at) WHERE (resolved_at IS NULL);
CREATE UNIQUE INDEX idx_queue_idempotency ON public.human_followup_queue USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX idx_emergency_business ON public.emergency_escalation USING btree (business_id);
CREATE INDEX idx_emergency_call ON public.emergency_escalation USING btree (call_id);
CREATE UNIQUE INDEX idx_emergency_idempotency ON public.emergency_escalation USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX idx_idempotency_expires ON public.idempotency_cache USING btree (expires_at);
CREATE INDEX idx_transcript_call ON public.transcript USING btree (call_id);
CREATE INDEX idx_turn_transcript ON public.transcript_turn USING btree (transcript_id);
CREATE INDEX idx_action_call ON public.action_log USING btree (call_id);
CREATE INDEX idx_action_timestamp ON public.action_log USING btree ("timestamp");
CREATE INDEX idx_action_name ON public.action_log USING btree (action_name);
CREATE INDEX idx_action_error ON public.action_log USING btree (error_code) WHERE (error_code IS NOT NULL);
CREATE INDEX idx_credentials_business ON public.business_credentials USING btree (business_id);
CREATE INDEX idx_phone_business ON public.business_phone_numbers USING btree (business_id);
CREATE INDEX idx_phone_number ON public.business_phone_numbers USING btree (phone_number);
CREATE INDEX idx_usage_business ON public.business_usage USING btree (business_id);
CREATE INDEX idx_usage_period ON public.business_usage USING btree (period_start);
CREATE INDEX idx_recording_business ON public.call_recording USING btree (business_id);
CREATE INDEX idx_recording_from ON public.call_recording USING btree (from_number);
CREATE INDEX idx_recording_customer ON public.call_recording USING btree (customer_id);
CREATE INDEX idx_recording_created ON public.call_recording USING btree (created_at DESC);
CREATE INDEX idx_recording_followup ON public.call_recording USING btree (requires_followup) WHERE (requires_followup = true);
CREATE INDEX idx_sms_campaign_business ON public.sms_campaign USING btree (business_id);
CREATE INDEX idx_sms_campaign_recipient_campaign ON public.sms_campaign_recipient USING btree (campaign_id);
CREATE INDEX idx_booking_reminder ON public.booking USING btree (status, reminder_sent, scheduled_start);
CREATE INDEX idx_sms_conversation_lookup ON public.sms_conversation USING btree (business_id, phone_number, created_at);
CREATE INDEX idx_customer_activity_lookup ON public.customer_activity USING btree (customer_id, created_at DESC);
CREATE INDEX idx_customer_activity_business ON public.customer_activity USING btree (business_id, created_at DESC);
CREATE INDEX idx_business_config_user_id ON public.business_config USING btree (user_id);
CREATE INDEX idx_time_entry_booking ON public.time_entry USING btree (booking_id);
CREATE INDEX idx_time_entry_customer ON public.time_entry USING btree (customer_id);
CREATE INDEX idx_call_recording_customer ON public.call_recording USING btree (customer_id);
CREATE INDEX idx_ai_suggestion_recording ON public.ai_suggestion USING btree (recording_id);
CREATE INDEX idx_ai_suggestion_customer ON public.ai_suggestion USING btree (customer_id);
CREATE INDEX idx_ai_suggestion_type ON public.ai_suggestion USING btree (suggestion_type);
CREATE INDEX idx_business_assigned_phone ON public.business_config USING btree (assigned_phone_number);
CREATE INDEX idx_time_entry_business ON public.time_entry USING btree (business_id);
CREATE INDEX idx_time_entry_date ON public.time_entry USING btree (work_date);
CREATE INDEX idx_call_recording_business ON public.call_recording USING btree (business_id);
CREATE INDEX idx_call_recording_created ON public.call_recording USING btree (created_at);
CREATE INDEX idx_ai_suggestion_business ON public.ai_suggestion USING btree (business_id);
CREATE INDEX idx_ai_suggestion_status ON public.ai_suggestion USING btree (status);
CREATE INDEX idx_ai_suggestion_created ON public.ai_suggestion USING btree (created_at);
CREATE INDEX idx_supplier_business ON public.supplier USING btree (business_id);
CREATE INDEX idx_supplier_product_business ON public.supplier_product USING btree (business_id);
CREATE INDEX idx_supplier_product_supplier ON public.supplier_product USING btree (supplier_id);
CREATE INDEX idx_supplier_product_name ON public.supplier_product USING btree (name);
CREATE INDEX idx_supplier_product_sku ON public.supplier_product USING btree (sku);
CREATE INDEX idx_invoice_business_id ON public.invoice USING btree (business_id);
CREATE INDEX idx_invoice_customer_id ON public.invoice USING btree (customer_id);
CREATE INDEX idx_invoice_due_date ON public.invoice USING btree (due_date);
CREATE INDEX idx_supplier_business_id ON public.supplier USING btree (business_id);
CREATE INDEX idx_material_order_business_id ON public.material_order USING btree (business_id);
CREATE INDEX idx_material_order_supplier_id ON public.material_order USING btree (supplier_id);
CREATE INDEX idx_time_entry_invoice_id ON public.time_entry USING btree (invoice_id);
CREATE INDEX idx_invoice_business ON public.invoice USING btree (business_id);
CREATE INDEX idx_invoice_customer ON public.invoice USING btree (customer_id);
CREATE INDEX idx_invoice_status ON public.invoice USING btree (status);
CREATE INDEX idx_material_order_business ON public.material_order USING btree (business_id);
CREATE INDEX idx_material_order_supplier ON public.material_order USING btree (supplier_id);
CREATE INDEX idx_material_order_status ON public.material_order USING btree (status);
CREATE INDEX idx_followup_queue_business ON public.human_followup_queue USING btree (business_id);
CREATE INDEX idx_activity_business ON public.activity USING btree (business_id);
CREATE INDEX idx_activity_customer ON public.activity USING btree (customer_id);
CREATE INDEX idx_sms_conversation_business ON public.sms_conversation USING btree (business_id);
CREATE INDEX idx_inbox_item_business ON public.inbox_item USING btree (business_id);
CREATE INDEX idx_impersonation_tokens_token ON public.impersonation_tokens USING btree (token);
CREATE INDEX idx_impersonation_tokens_admin ON public.impersonation_tokens USING btree (admin_user_id);
CREATE INDEX idx_impersonation_tokens_expires ON public.impersonation_tokens USING btree (expires_at);
CREATE INDEX idx_admin_actions_admin ON public.admin_actions_log USING btree (admin_user_id);
CREATE INDEX idx_admin_actions_business ON public.admin_actions_log USING btree (target_business_id);
CREATE INDEX idx_admin_actions_action ON public.admin_actions_log USING btree (action);
CREATE INDEX idx_admin_actions_created ON public.admin_actions_log USING btree (created_at DESC);
CREATE INDEX idx_invoice_fortnox_sync ON public.invoice USING btree (business_id, fortnox_invoice_number) WHERE (fortnox_invoice_number IS NULL);
CREATE INDEX idx_invoice_fortnox_docnum ON public.invoice USING btree (fortnox_document_number) WHERE (fortnox_document_number IS NOT NULL);
CREATE INDEX idx_work_type_business ON public.work_type USING btree (business_id);
CREATE INDEX idx_time_entry_work_type ON public.time_entry USING btree (work_type_id);
CREATE INDEX idx_time_entry_invoice ON public.time_entry USING btree (invoice_id);
CREATE INDEX idx_time_entry_uninvoiced ON public.time_entry USING btree (business_id, invoiced) WHERE (invoiced = false);
CREATE INDEX idx_project_business ON public.project USING btree (business_id);
CREATE INDEX idx_project_customer ON public.project USING btree (customer_id);
CREATE INDEX idx_project_status ON public.project USING btree (business_id, status);
CREATE INDEX idx_milestone_project ON public.project_milestone USING btree (project_id);
CREATE INDEX idx_milestone_business ON public.project_milestone USING btree (business_id);
CREATE INDEX idx_change_project ON public.project_change USING btree (project_id);
CREATE INDEX idx_change_business ON public.project_change USING btree (business_id);
CREATE INDEX idx_time_entry_project ON public.time_entry USING btree (project_id);
CREATE INDEX idx_time_entry_milestone ON public.time_entry USING btree (milestone_id);
CREATE INDEX idx_supplier_connection_business ON public.supplier_connection USING btree (business_id);
CREATE INDEX idx_supplier_connection_key ON public.supplier_connection USING btree (supplier_key);
CREATE INDEX idx_grossist_product_business ON public.grossist_product USING btree (business_id);
CREATE INDEX idx_grossist_product_connection ON public.grossist_product USING btree (connection_id);
CREATE INDEX idx_grossist_product_supplier_key ON public.grossist_product USING btree (supplier_key);
CREATE INDEX idx_grossist_product_sku ON public.grossist_product USING btree (sku);
CREATE INDEX idx_grossist_product_ean ON public.grossist_product USING btree (ean);
CREATE INDEX idx_grossist_product_external ON public.grossist_product USING btree (connection_id, external_id);
CREATE INDEX idx_project_material_project ON public.project_material USING btree (project_id);
CREATE INDEX idx_project_material_business ON public.project_material USING btree (business_id);
CREATE INDEX idx_project_material_invoiced ON public.project_material USING btree (project_id) WHERE (invoiced = false);
CREATE INDEX idx_business_users_business ON public.business_users USING btree (business_id);
CREATE INDEX idx_business_users_user ON public.business_users USING btree (user_id);
CREATE INDEX idx_business_users_email ON public.business_users USING btree (email);
CREATE INDEX idx_business_users_invite_token ON public.business_users USING btree (invite_token);
CREATE INDEX idx_project_assignment_business ON public.project_assignment USING btree (business_id);
CREATE INDEX idx_project_assignment_order ON public.project_assignment USING btree (order_id);
CREATE INDEX idx_project_assignment_user ON public.project_assignment USING btree (business_user_id);
CREATE INDEX idx_schedule_entry_business ON public.schedule_entry USING btree (business_id);
CREATE INDEX idx_schedule_entry_user ON public.schedule_entry USING btree (business_user_id);
CREATE INDEX idx_schedule_entry_dates ON public.schedule_entry USING btree (start_datetime, end_datetime);
CREATE INDEX idx_schedule_entry_project ON public.schedule_entry USING btree (project_id);
CREATE INDEX idx_time_off_request_business ON public.time_off_request USING btree (business_id);
CREATE INDEX idx_time_off_request_user ON public.time_off_request USING btree (business_user_id);
CREATE INDEX idx_time_off_request_dates ON public.time_off_request USING btree (start_date, end_date);
CREATE INDEX idx_project_document_business ON public.project_document USING btree (business_id);
CREATE INDEX idx_project_document_order ON public.project_document USING btree (order_id);
CREATE INDEX idx_project_log_business ON public.project_log USING btree (business_id);
CREATE INDEX idx_project_log_order ON public.project_log USING btree (order_id);
CREATE INDEX idx_project_log_date ON public.project_log USING btree (date);
CREATE INDEX idx_checklist_template_business ON public.checklist_template USING btree (business_id);
CREATE INDEX idx_checklist_template_branch ON public.checklist_template USING btree (branch);
CREATE INDEX idx_project_checklist_business ON public.project_checklist USING btree (business_id);
CREATE INDEX idx_project_checklist_order ON public.project_checklist USING btree (order_id);
CREATE INDEX idx_calendar_connection_business ON public.calendar_connection USING btree (business_id);
CREATE INDEX idx_calendar_connection_user ON public.calendar_connection USING btree (business_user_id);
CREATE INDEX idx_schedule_entry_google ON public.schedule_entry USING btree (google_event_id);
CREATE INDEX idx_job_template_business ON public.job_template USING btree (business_id);
CREATE INDEX idx_job_template_branch ON public.job_template USING btree (branch);
CREATE INDEX idx_customer_portal_token ON public.customer USING btree (portal_token);
CREATE INDEX idx_customer_message_customer ON public.customer_message USING btree (customer_id);
CREATE INDEX idx_customer_message_business ON public.customer_message USING btree (business_id);
CREATE INDEX idx_pipeline_stage_business ON public.pipeline_stage USING btree (business_id);
CREATE INDEX idx_deal_business ON public.deal USING btree (business_id);
CREATE INDEX idx_deal_stage ON public.deal USING btree (stage_id);
CREATE INDEX idx_deal_customer ON public.deal USING btree (customer_id);
CREATE INDEX idx_pipeline_activity_deal ON public.pipeline_activity USING btree (deal_id);
CREATE INDEX idx_pipeline_activity_business ON public.pipeline_activity USING btree (business_id);
CREATE INDEX idx_document_template_business ON public.document_template USING btree (business_id);
CREATE INDEX idx_document_template_category ON public.document_template USING btree (category_id);
CREATE INDEX idx_generated_document_business ON public.generated_document USING btree (business_id);
CREATE INDEX idx_generated_document_project ON public.generated_document USING btree (project_id);
CREATE INDEX idx_generated_document_customer ON public.generated_document USING btree (customer_id);
CREATE INDEX idx_generated_document_template ON public.generated_document USING btree (template_id);
CREATE INDEX idx_automation_activity_business ON public.automation_activity USING btree (business_id);
CREATE INDEX idx_automation_activity_created ON public.automation_activity USING btree (created_at);
CREATE INDEX idx_quotes_updated_at ON public.quotes USING btree (updated_at);
CREATE INDEX idx_customer_document_customer ON public.customer_document USING btree (customer_id);
CREATE INDEX idx_customer_document_business ON public.customer_document USING btree (business_id);
CREATE INDEX idx_auto_approve_daily_biz_date ON public.auto_approve_daily_count USING btree (business_id, count_date);
CREATE INDEX idx_nurture_seq_biz ON public.nurture_sequence USING btree (business_id);
CREATE INDEX idx_nurture_enroll_biz ON public.nurture_enrollment USING btree (business_id);
CREATE INDEX idx_nurture_enroll_next ON public.nurture_enrollment USING btree (next_action_at) WHERE (status = 'active'::text);
CREATE INDEX idx_comm_log_biz ON public.communication_log USING btree (business_id, created_at DESC);
CREATE INDEX idx_notification_business ON public.notification USING btree (business_id, is_read, created_at DESC);
CREATE INDEX idx_notification_user ON public.notification USING btree (user_id, is_read, created_at DESC);
CREATE INDEX idx_customer_tag_business ON public.customer_tag USING btree (business_id);
CREATE INDEX idx_customer_tag_assignment_customer ON public.customer_tag_assignment USING btree (customer_id);
CREATE INDEX idx_customer_tag_assignment_tag ON public.customer_tag_assignment USING btree (tag_id);
CREATE INDEX idx_warranty_business ON public.warranty USING btree (business_id);
CREATE INDEX idx_warranty_customer ON public.warranty USING btree (customer_id);
CREATE INDEX idx_warranty_end_date ON public.warranty USING btree (end_date);
CREATE INDEX idx_email_template_business ON public.email_template USING btree (business_id);
CREATE INDEX idx_subcontractor_business ON public.subcontractor USING btree (business_id);
CREATE INDEX idx_subcontractor_assignment_business ON public.subcontractor_assignment USING btree (business_id);
CREATE INDEX idx_subcontractor_assignment_sub ON public.subcontractor_assignment USING btree (subcontractor_id);
CREATE INDEX idx_task_business ON public.task USING btree (business_id);
CREATE INDEX idx_task_deal ON public.task USING btree (deal_id);
CREATE INDEX idx_task_customer ON public.task USING btree (customer_id);
CREATE INDEX idx_task_status ON public.task USING btree (business_id, status);
CREATE INDEX idx_deal_note_deal ON public.deal_note USING btree (deal_id);
CREATE INDEX idx_deal_note_business ON public.deal_note USING btree (business_id);
CREATE INDEX idx_lead_source_business ON public.lead_source USING btree (business_id);
CREATE INDEX idx_lead_source_email ON public.lead_source USING btree (inbound_email);
CREATE INDEX idx_review_request_business ON public.review_request USING btree (business_id);
CREATE INDEX idx_review_request_customer ON public.review_request USING btree (customer_id);
CREATE INDEX idx_inventory_business ON public.inventory USING btree (business_id);
CREATE INDEX idx_invtx_inventory ON public.inventory_transaction USING btree (inventory_id);
CREATE INDEX idx_invtx_project ON public.inventory_transaction USING btree (project_id);
CREATE INDEX idx_project_cost_project ON public.project_cost USING btree (project_id);
CREATE INDEX idx_time_entry_approval ON public.time_entry USING btree (business_id, approval_status) WHERE (approval_status = 'pending'::text);
CREATE INDEX idx_widget_conv_business ON public.widget_conversation USING btree (business_id, created_at);
CREATE INDEX idx_widget_conv_session ON public.widget_conversation USING btree (business_id, session_id);
CREATE UNIQUE INDEX idx_calendar_connection_unique ON public.calendar_connection USING btree (business_user_id, provider);
CREATE INDEX idx_storefront_slug ON public.storefront USING btree (slug) WHERE (slug IS NOT NULL);
CREATE INDEX idx_storefront_business ON public.storefront USING btree (business_id);
CREATE INDEX idx_project_health ON public.project USING btree (business_id, ai_health_score) WHERE (status = ANY (ARRAY['planning'::text, 'active'::text]));
CREATE INDEX idx_ai_log_project ON public.project_ai_log USING btree (project_id);
CREATE INDEX idx_ai_log_business ON public.project_ai_log USING btree (business_id, created_at DESC);
CREATE INDEX idx_quote_items_quote_sort ON public.quote_items USING btree (quote_id, sort_order);
CREATE INDEX idx_quote_templates_business ON public.quote_templates USING btree (business_id);
CREATE INDEX idx_quote_standard_texts_biz_type ON public.quote_standard_texts USING btree (business_id, text_type);
CREATE UNIQUE INDEX idx_quote_standard_texts_unique ON public.quote_standard_texts USING btree (business_id, text_type, name);
CREATE INDEX idx_invoice_reminders_invoice ON public.invoice_reminders USING btree (invoice_id);
CREATE INDEX idx_invoice_reminders_business ON public.invoice_reminders USING btree (business_id);
CREATE INDEX idx_travel_entry_business ON public.travel_entry USING btree (business_id);
CREATE INDEX idx_travel_entry_user ON public.travel_entry USING btree (business_user_id);
CREATE INDEX idx_travel_entry_date ON public.travel_entry USING btree (date);
CREATE INDEX idx_time_entry_check_in ON public.time_entry USING btree (check_in_time) WHERE ((check_in_time IS NOT NULL) AND (check_out_time IS NULL));
CREATE INDEX idx_time_entry_work_category ON public.time_entry USING btree (work_category);
CREATE INDEX idx_agent_runs_business ON public.agent_runs USING btree (business_id);
CREATE INDEX idx_agent_runs_trigger ON public.agent_runs USING btree (trigger_type);
CREATE INDEX idx_agent_runs_created ON public.agent_runs USING btree (created_at DESC);
CREATE INDEX idx_conversations_business ON public.conversations USING btree (business_id);
CREATE INDEX idx_conversations_customer ON public.conversations USING btree (customer_id);
CREATE INDEX idx_conversations_type ON public.conversations USING btree (type);
CREATE INDEX idx_conversations_phone ON public.conversations USING btree (phone_number);
CREATE INDEX idx_conversations_created ON public.conversations USING btree (created_at DESC);
CREATE INDEX idx_scheduled_actions_business ON public.scheduled_actions USING btree (business_id);
CREATE INDEX idx_scheduled_actions_status ON public.scheduled_actions USING btree (status);
CREATE INDEX idx_scheduled_actions_scheduled ON public.scheduled_actions USING btree (scheduled_for);
CREATE INDEX idx_scheduled_actions_pending ON public.scheduled_actions USING btree (status, scheduled_for) WHERE (status = 'pending'::text);
CREATE INDEX idx_leads_business ON public.leads USING btree (business_id);
CREATE INDEX idx_leads_status ON public.leads USING btree (business_id, status);
CREATE INDEX idx_leads_score ON public.leads USING btree (business_id, score DESC);
CREATE INDEX idx_leads_conversation ON public.leads USING btree (conversation_id);
CREATE INDEX idx_leads_customer ON public.leads USING btree (customer_id);
CREATE INDEX idx_lead_activities_lead ON public.lead_activities USING btree (lead_id);
CREATE INDEX idx_lead_activities_business ON public.lead_activities USING btree (business_id);
CREATE INDEX idx_lead_scoring_rules_business ON public.lead_scoring_rules USING btree (business_id);
CREATE INDEX idx_automation_rules_business ON public.automation_rules USING btree (business_id);
CREATE INDEX idx_automation_rules_enabled ON public.automation_rules USING btree (business_id, enabled) WHERE (enabled = true);
CREATE INDEX idx_automation_queue_business ON public.automation_queue USING btree (business_id);
CREATE INDEX idx_automation_queue_status ON public.automation_queue USING btree (status);
CREATE INDEX idx_automation_queue_scheduled ON public.automation_queue USING btree (scheduled_at);
CREATE INDEX idx_automation_queue_pending ON public.automation_queue USING btree (status, scheduled_at) WHERE (status = 'pending'::text);
CREATE INDEX idx_automation_queue_target ON public.automation_queue USING btree (target_id, rule_type);
CREATE INDEX idx_booking_google_event ON public.booking USING btree (google_event_id) WHERE (google_event_id IS NOT NULL);
CREATE UNIQUE INDEX idx_agent_runs_idempotency ON public.agent_runs USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX idx_sms_queue_pending ON public.sms_queue USING btree (status, send_after) WHERE (status = 'queued'::text);
CREATE INDEX idx_sms_log_business ON public.sms_log USING btree (business_id);
CREATE INDEX idx_sms_log_phone_to ON public.sms_log USING btree (phone_to);
CREATE INDEX idx_sms_log_created ON public.sms_log USING btree (created_at);
CREATE INDEX idx_sms_log_direction ON public.sms_log USING btree (business_id, direction);
CREATE INDEX idx_sms_log_status ON public.sms_log USING btree (status);
CREATE INDEX idx_sms_conv_business ON public.sms_conversation USING btree (business_id);
CREATE INDEX idx_sms_conv_phone ON public.sms_conversation USING btree (business_id, phone_number);
CREATE INDEX idx_sms_conv_created ON public.sms_conversation USING btree (created_at);
CREATE INDEX idx_task_activity_task ON public.task_activity_log USING btree (task_id);
CREATE INDEX idx_task_activity_business ON public.task_activity_log USING btree (business_id);
CREATE INDEX idx_task_activity_created ON public.task_activity_log USING btree (created_at DESC);
CREATE INDEX idx_gmail_imported_business ON public.gmail_imported_message USING btree (business_id);
CREATE INDEX idx_customer_document_lead ON public.customer_document USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX idx_inbox_item_status ON public.inbox_item USING btree (business_id, status);
CREATE INDEX idx_inbox_item_created ON public.inbox_item USING btree (created_at DESC);
CREATE INDEX idx_customer_number ON public.customer USING btree (business_id, customer_number);
CREATE INDEX idx_lead_project_number ON public.leads USING btree (business_id, project_number);
CREATE INDEX idx_v3_automation_rules_business ON public.v3_automation_rules USING btree (business_id, is_active);
CREATE INDEX idx_v3_automation_rules_trigger ON public.v3_automation_rules USING btree (business_id, trigger_type) WHERE (is_active = true);
CREATE INDEX idx_v3_automation_logs_business ON public.v3_automation_logs USING btree (business_id, created_at DESC);
CREATE INDEX idx_v3_automation_logs_rule ON public.v3_automation_logs USING btree (rule_id, created_at DESC);
CREATE INDEX idx_pipeline_stages_business ON public.pipeline_stages USING btree (business_id);
CREATE INDEX idx_pipeline_stages_key ON public.pipeline_stages USING btree (business_id, key);
CREATE INDEX idx_leads_pipeline_stage ON public.leads USING btree (pipeline_stage_key);
CREATE INDEX idx_agent_context_business ON public.agent_context USING btree (business_id);
CREATE INDEX idx_learning_business ON public.learning_events USING btree (business_id);
CREATE INDEX idx_learning_category ON public.learning_events USING btree (business_id, preference_category);
CREATE INDEX idx_agent_runs_agent_type ON public.agent_runs USING btree (agent_type);
CREATE INDEX idx_fortnox_sync_business ON public.fortnox_sync USING btree (business_id, sync_status);
CREATE INDEX idx_pricing_intel_business ON public.pricing_intelligence USING btree (business_id);
CREATE INDEX idx_referrals_referrer ON public.referrals USING btree (referrer_business_id);
CREATE INDEX idx_email_conv_business ON public.email_conversations USING btree (business_id, status);
CREATE INDEX idx_email_conv_message ON public.email_conversations USING btree (gmail_message_id);
CREATE INDEX idx_email_conv_customer ON public.email_conversations USING btree (customer_id);
CREATE INDEX idx_email_conv_received ON public.email_conversations USING btree (business_id, received_at DESC);
CREATE INDEX idx_partners_code ON public.partners USING btree (referral_code);
CREATE INDEX idx_partners_email ON public.partners USING btree (email);
CREATE INDEX idx_referrals_partner ON public.referrals USING btree (partner_id);
CREATE INDEX idx_quotes_parent ON public.quotes USING btree (parent_quote_id);
CREATE INDEX idx_vehicles_business ON public.vehicles USING btree (business_id);
CREATE INDEX idx_vehicle_reports_business ON public.vehicle_reports USING btree (business_id, report_date);
CREATE INDEX idx_vehicle_reports_project ON public.vehicle_reports USING btree (project_id);
CREATE INDEX idx_vehicle_reports_vehicle ON public.vehicle_reports USING btree (vehicle_id);
CREATE UNIQUE INDEX idx_change_sign_token ON public.project_change USING btree (sign_token) WHERE (sign_token IS NOT NULL);
CREATE UNIQUE INDEX idx_change_ata_number ON public.project_change USING btree (project_id, ata_number) WHERE (ata_number IS NOT NULL);
CREATE INDEX idx_allowance_types_business ON public.allowance_types USING btree (business_id);
CREATE INDEX idx_allowance_reports_business ON public.allowance_reports USING btree (business_id, report_date);
CREATE INDEX idx_allowance_reports_project ON public.allowance_reports USING btree (project_id);
CREATE INDEX idx_allowance_reports_user ON public.allowance_reports USING btree (business_user_id);
CREATE INDEX idx_work_orders_project ON public.work_orders USING btree (project_id);
CREATE INDEX idx_work_orders_business ON public.work_orders USING btree (business_id, status);
CREATE INDEX idx_form_templates_business ON public.form_templates USING btree (business_id);
CREATE INDEX idx_form_submissions_business ON public.form_submissions USING btree (business_id);
CREATE INDEX idx_form_submissions_project ON public.form_submissions USING btree (project_id);
CREATE INDEX idx_supplier_invoices_project ON public.supplier_invoices USING btree (project_id);
CREATE INDEX idx_supplier_invoices_business ON public.supplier_invoices USING btree (business_id, status);
CREATE INDEX idx_project_canvas_project ON public.canvas_items USING btree (project_id);
CREATE INDEX idx_project_canvas_business ON public.canvas_items USING btree (business_id);
CREATE INDEX idx_canvas_entity ON public.canvas_items USING btree (business_id, entity_type, entity_id);
CREATE INDEX idx_project_lead_id ON public.project USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX idx_push_tokens_business_id ON public.push_tokens USING btree (business_id);
CREATE INDEX idx_partner_events_partner ON public.partner_events USING btree (partner_id);
CREATE INDEX idx_partner_events_type ON public.partner_events USING btree (event_type);
CREATE INDEX idx_leads_lead_source ON public.leads USING btree (lead_source_id);
CREATE INDEX idx_lead_sources_business ON public.lead_sources USING btree (business_id);
CREATE INDEX idx_lead_sources_portal_code ON public.lead_sources USING btree (portal_code);
CREATE INDEX idx_price_lists_v2_business ON public.price_lists_v2 USING btree (business_id);
CREATE INDEX idx_price_lists_v2_segment ON public.price_lists_v2 USING btree (segment_id);
CREATE INDEX idx_price_list_items_v2_list ON public.price_list_items_v2 USING btree (price_list_id);
CREATE INDEX idx_customer_segment ON public.customer USING btree (segment_id);
CREATE INDEX idx_customer_price_list ON public.customer USING btree (price_list_id);
CREATE INDEX idx_customer_segments_biz ON public.customer_segments USING btree (business_id);
CREATE INDEX idx_contract_types_biz ON public.contract_types USING btree (business_id);
CREATE INDEX idx_pending_approvals_business ON public.pending_approvals USING btree (business_id, status);
CREATE INDEX idx_pending_approvals_expires ON public.pending_approvals USING btree (expires_at) WHERE (status = 'pending'::text);
CREATE INDEX idx_pending_approvals_package ON public.pending_approvals USING btree (package_id) WHERE (package_id IS NOT NULL);
CREATE INDEX idx_project_stages_project ON public.project_stages USING btree (project_id);
CREATE INDEX idx_project_photos_project ON public.project_photos USING btree (project_id);
CREATE INDEX idx_quote_tracking_quote ON public.quote_tracking_events USING btree (quote_id);
CREATE INDEX idx_quote_tracking_created ON public.quote_tracking_events USING btree (created_at);
CREATE INDEX idx_seasonality_insights_biz ON public.seasonality_insights USING btree (business_id);
CREATE INDEX idx_seasonal_campaigns_biz ON public.seasonal_campaigns USING btree (business_id);
CREATE INDEX idx_inventory_items_business ON public.inventory_items USING btree (business_id);
CREATE INDEX idx_inventory_items_location ON public.inventory_items USING btree (location_id);
CREATE INDEX idx_inventory_movements_item ON public.inventory_movements USING btree (item_id);
CREATE INDEX idx_inventory_movements_project ON public.inventory_movements USING btree (project_id);
CREATE INDEX idx_checkins_business ON public.time_checkins USING btree (business_id);
CREATE INDEX idx_checkins_user ON public.time_checkins USING btree (user_id);
CREATE INDEX idx_checkins_status ON public.time_checkins USING btree (status);
CREATE INDEX idx_checkins_date ON public.time_checkins USING btree (checked_in_at);
CREATE INDEX idx_field_reports_business ON public.field_reports USING btree (business_id);
CREATE INDEX idx_field_reports_token ON public.field_reports USING btree (signature_token);
CREATE INDEX idx_field_reports_project ON public.field_reports USING btree (project_id);
CREATE INDEX idx_field_report_photos_report ON public.field_report_photos USING btree (report_id);
CREATE INDEX idx_business_users_skills ON public.business_users USING gin (skills);
CREATE INDEX idx_leads_outbound_business ON public.leads_outbound USING btree (business_id, status);
CREATE INDEX idx_leads_outbound_batch ON public.leads_outbound USING btree (business_id, batch_id);
CREATE INDEX idx_leads_monthly_business ON public.leads_monthly_usage USING btree (business_id, month);
CREATE INDEX idx_neighbour_campaigns_biz ON public.leads_neighbour_campaigns USING btree (business_id);
CREATE INDEX idx_neighbour_campaigns_status ON public.leads_neighbour_campaigns USING btree (status);
CREATE INDEX idx_manual_suppliers_biz ON public.manual_suppliers USING btree (business_id);
CREATE INDEX idx_manual_supplier_products_biz ON public.manual_supplier_products USING btree (business_id);
CREATE INDEX idx_manual_supplier_products_watch ON public.manual_supplier_products USING btree (watch_price) WHERE (watch_price = true);
CREATE INDEX idx_customer_ltv ON public.customer USING btree (business_id, lifetime_value DESC);
CREATE INDEX idx_customer_last_job ON public.customer USING btree (business_id, last_job_date);
CREATE INDEX idx_agent_memories_business ON public.agent_memories USING btree (business_id, agent_id);
CREATE INDEX idx_agent_memories_type ON public.agent_memories USING btree (business_id, memory_type);
CREATE INDEX idx_agent_messages_to ON public.agent_messages USING btree (business_id, to_agent, status);
CREATE INDEX idx_agent_messages_created ON public.agent_messages USING btree (business_id, created_at DESC);
CREATE INDEX idx_automation_rules_agent ON public.v3_automation_rules USING btree (agent_id);
CREATE INDEX idx_automation_logs_agent ON public.v3_automation_logs USING btree (agent_id);
CREATE INDEX idx_agent_runs_agent ON public.agent_runs USING btree (agent_id);
CREATE INDEX idx_sms_usage_business ON public.sms_usage USING btree (business_id);
CREATE INDEX idx_sms_usage_month ON public.sms_usage USING btree (month);
CREATE INDEX idx_project_document_project ON public.project_document USING btree (project_id);
CREATE INDEX idx_quotes_sign_token ON public.quotes USING btree (sign_token);
CREATE INDEX idx_project_profitability ON public.project USING btree (profitability_status) WHERE (status = 'active'::text);
CREATE INDEX idx_deal_business_number ON public.deal USING btree (business_id, deal_number);
CREATE INDEX idx_quotes_accepted ON public.quotes USING btree (business_id, status) WHERE (status = 'accepted'::text);
CREATE INDEX idx_quotes_category ON public.quotes USING btree (business_id) WHERE (status = ANY (ARRAY['accepted'::text, 'completed'::text]));
CREATE INDEX idx_project_assignment_project ON public.project_assignment USING btree (project_id);
CREATE INDEX idx_deal_auto_tasks_deal ON public.deal_automation_tasks USING btree (deal_id) WHERE ((executed_at IS NULL) AND (cancelled_at IS NULL));
CREATE INDEX idx_deal_auto_tasks_schedule ON public.deal_automation_tasks USING btree (scheduled_at) WHERE ((executed_at IS NULL) AND (cancelled_at IS NULL));
CREATE INDEX idx_deal_project ON public.deal USING btree (project_id) WHERE (project_id IS NOT NULL);
CREATE INDEX idx_project_deal ON public.project USING btree (deal_id) WHERE (deal_id IS NOT NULL);
CREATE INDEX idx_deal_flow_business ON public.deal_flow USING btree (business_id);
CREATE INDEX idx_deal_flow_deal ON public.deal_flow USING btree (deal_id);
CREATE INDEX idx_deal_flow_status ON public.deal_flow USING btree (status);
CREATE INDEX idx_deal_flow_log_deal ON public.deal_flow_log USING btree (deal_id);
CREATE INDEX idx_deal_flow_log_business ON public.deal_flow_log USING btree (business_id);
CREATE INDEX idx_deal_flow_log_step ON public.deal_flow_log USING btree (step_key);
CREATE INDEX idx_project_events_project ON public.project_events USING btree (project_id, created_at DESC);
CREATE INDEX idx_project_events_business ON public.project_events USING btree (business_id, created_at DESC);
CREATE INDEX idx_leads_phone_business ON public.leads USING btree (phone, business_id) WHERE (phone IS NOT NULL);
CREATE INDEX idx_customer_phone_business ON public.customer USING btree (phone_number, business_id) WHERE (phone_number IS NOT NULL);
CREATE INDEX idx_customer_email_business ON public.customer USING btree (email, business_id) WHERE (email IS NOT NULL);
CREATE INDEX idx_pending_approvals_matte ON public.pending_approvals USING btree (business_id, status, created_at DESC) WHERE (status = 'pending'::text);
CREATE INDEX idx_invoice_overdue ON public.invoice USING btree (business_id, status, due_date) WHERE (status = 'sent'::text);
CREATE INDEX idx_quotes_stale ON public.quotes USING btree (business_id, status, created_at) WHERE (status = 'sent'::text);
CREATE INDEX idx_leads_active ON public.leads USING btree (business_id, status, score) WHERE (status <> ALL (ARRAY['won'::text, 'lost'::text, 'completed'::text]));
CREATE INDEX idx_quotes_lead ON public.quotes USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX idx_deal_lead ON public.deal USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX idx_calendar_watches_channel ON public.calendar_watches USING btree (channel_id) WHERE (is_active = true);
CREATE INDEX idx_calendar_watches_business ON public.calendar_watches USING btree (business_id);
CREATE INDEX idx_calendar_watches_expires ON public.calendar_watches USING btree (expires_at) WHERE (is_active = true);
CREATE INDEX idx_task_assigned ON public.task USING btree (assigned_to) WHERE (assigned_to IS NOT NULL);
CREATE INDEX idx_task_created_by ON public.task USING btree (created_by) WHERE (created_by IS NOT NULL);
CREATE INDEX idx_task_visibility ON public.task USING btree (business_id, visibility);
CREATE INDEX idx_landing_leads_email ON public.landing_leads USING btree (email);
CREATE INDEX idx_landing_leads_source ON public.landing_leads USING btree (source);
CREATE INDEX idx_monthly_reviews_business ON public.monthly_reviews USING btree (business_id, month DESC);
CREATE INDEX idx_leads_category ON public.leads USING btree (business_id, category) WHERE (category IS NOT NULL);
CREATE INDEX idx_lead_sources_type ON public.lead_sources USING btree (business_id, source_type);
CREATE INDEX idx_job_types_business ON public.job_types USING btree (business_id, is_active);
CREATE INDEX idx_business_users_specialties ON public.business_users USING gin (specialties);
CREATE INDEX idx_deal_assigned_to ON public.deal USING btree (business_id, assigned_to) WHERE (assigned_to IS NOT NULL);
CREATE INDEX idx_matte_conversations_business_updated ON public.matte_conversations USING btree (business_id, updated_at DESC);
CREATE INDEX idx_matte_messages_conversation ON public.matte_messages USING btree (conversation_id, created_at);
CREATE INDEX idx_quotes_deal_id ON public.quotes USING btree (deal_id) WHERE (deal_id IS NOT NULL);
CREATE INDEX idx_project_workflow_stage ON public.project USING btree (current_workflow_stage_id) WHERE (current_workflow_stage_id IS NOT NULL);
CREATE INDEX idx_stage_automations ON public.project_stage_automations USING btree (stage_id, business_id);
CREATE INDEX idx_portal_notif_customer ON public.portal_notification_log USING btree (customer_id, sent_at DESC);
CREATE INDEX idx_portal_notif_business ON public.portal_notification_log USING btree (business_id, sent_at DESC);
CREATE INDEX idx_fortnox_log_business ON public.fortnox_api_log USING btree (business_id, created_at DESC);
CREATE INDEX idx_fortnox_log_errors ON public.fortnox_api_log USING btree (business_id, created_at DESC) WHERE (error_message IS NOT NULL);
CREATE INDEX idx_products_business ON public.products USING btree (business_id, is_active);
CREATE INDEX idx_products_search ON public.products USING gin (to_tsvector('simple'::regconfig, name));
CREATE INDEX idx_quote_items_linked_product ON public.quote_items USING btree (linked_product_id) WHERE (linked_product_id IS NOT NULL);
CREATE INDEX idx_agent_threads_customer ON public.agent_threads USING btree (business_id, customer_id);
CREATE INDEX idx_agent_threads_project ON public.agent_threads USING btree (business_id, project_id) WHERE (project_id IS NOT NULL);
CREATE INDEX idx_agent_handoffs_thread ON public.agent_handoffs USING btree (thread_id, created_at DESC);
CREATE INDEX idx_thread_messages_thread ON public.thread_message USING btree (thread_id, created_at);
CREATE INDEX idx_thread_messages_business ON public.thread_message USING btree (business_id, created_at DESC);
CREATE INDEX idx_project_job_type ON public.project USING btree (business_id, job_type) WHERE (job_type IS NOT NULL);
CREATE INDEX idx_booking_on_my_way ON public.booking USING btree (business_id, on_my_way_at) WHERE (on_my_way_at IS NOT NULL);
CREATE INDEX idx_booking_project ON public.booking USING btree (business_id, project_id) WHERE (project_id IS NOT NULL);
CREATE INDEX idx_booking_kind ON public.booking USING btree (business_id, kind) WHERE (kind <> 'standard'::text);
CREATE INDEX idx_customer_review_request_sent_at ON public.customer USING btree (review_request_sent_at) WHERE (review_request_sent_at IS NULL);
CREATE INDEX idx_business_knowledge_business ON public.business_knowledge USING btree (business_id, agent_id, status);
CREATE INDEX idx_business_knowledge_created ON public.business_knowledge USING btree (business_id, created_at DESC);
CREATE INDEX idx_business_knowledge_active ON public.business_knowledge USING btree (business_id, agent_id) WHERE (status = 'active'::text);
CREATE INDEX idx_business_insights_business ON public.business_insights USING btree (business_id, generated_at DESC);
CREATE INDEX idx_business_insights_active ON public.business_insights USING btree (business_id, expires_at) WHERE (feedback IS NULL);
CREATE INDEX idx_bk_dedup ON public.business_knowledge USING btree (business_id, agent_id, dedup_key) WHERE ((status = 'active'::text) AND (dedup_key IS NOT NULL));
CREATE INDEX idx_imp_tokens_token ON public.impersonation_tokens USING btree (token) WHERE (used = false);
CREATE INDEX idx_imp_tokens_admin ON public.impersonation_tokens USING btree (admin_user_id, created_at DESC);
CREATE INDEX idx_admin_imp_log_admin ON public.admin_impersonation_log USING btree (admin_user_id, started_at DESC);
CREATE INDEX idx_admin_imp_log_target ON public.admin_impersonation_log USING btree (target_business_id, started_at DESC);
CREATE INDEX idx_invoice_project ON public.invoice USING btree (project_id) WHERE (project_id IS NOT NULL);
CREATE INDEX idx_business_config_active ON public.business_config USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_invoice_fortnox_sync_failed ON public.invoice USING btree (business_id, fortnox_sync_status) WHERE (fortnox_sync_status = 'failed'::text);
CREATE INDEX idx_business_patterns_business ON public.business_patterns USING btree (business_id);
CREATE INDEX idx_business_patterns_calculated ON public.business_patterns USING btree (last_calculated_at DESC);
CREATE INDEX idx_business_patterns_active ON public.business_patterns USING btree (business_id, pattern_key) WHERE (is_stale = false);
CREATE INDEX idx_ad_analyses_user_id ON public.ad_analyses USING btree (user_id);
CREATE INDEX idx_ad_analyses_created_at ON public.ad_analyses USING btree (created_at DESC);
CREATE INDEX idx_generated_copies_user_id ON public.generated_copies USING btree (user_id);
CREATE INDEX idx_campaign_plans_user_id ON public.campaign_plans USING btree (user_id);
CREATE INDEX idx_personas_is_default ON public.personas USING btree (is_default);
CREATE INDEX idx_templates_user_id ON public.templates USING btree (user_id);
CREATE INDEX idx_templates_updated_at ON public.templates USING btree (updated_at DESC);
CREATE INDEX idx_templates_favorite ON public.templates USING btree (is_favorite) WHERE (is_favorite = true);
CREATE INDEX idx_production_jobs_user_id ON public.production_jobs USING btree (user_id);
CREATE INDEX idx_production_jobs_status ON public.production_jobs USING btree (status);
CREATE INDEX idx_production_jobs_created_at ON public.production_jobs USING btree (created_at DESC);
CREATE INDEX idx_production_jobs_template ON public.production_jobs USING btree (template_id);
CREATE INDEX idx_qa_runs_user_id ON public.qa_runs USING btree (user_id);
CREATE INDEX idx_qa_runs_status ON public.qa_runs USING btree (status);
CREATE INDEX idx_qa_runs_creative ON public.qa_runs USING btree (creative_kind, creative_ref);
CREATE INDEX idx_qa_runs_created_at ON public.qa_runs USING btree (created_at DESC);
CREATE INDEX idx_ai_gen_user ON public.ai_generations USING btree (user_id);
CREATE INDEX idx_ai_gen_cache ON public.ai_generations USING btree (cache_key) WHERE ((cache_hit = false) AND (status = 'success'::text));
CREATE INDEX idx_ai_gen_provider ON public.ai_generations USING btree (provider);
CREATE INDEX idx_ai_gen_created_at ON public.ai_generations USING btree (created_at DESC);
CREATE INDEX idx_master_creatives_user ON public.master_creatives USING btree (created_by);
CREATE INDEX idx_master_creatives_updated ON public.master_creatives USING btree (updated_at DESC);
CREATE INDEX idx_briefs_status ON public.creative_briefs USING btree (status);
CREATE INDEX idx_briefs_user ON public.creative_briefs USING btree (created_by);
CREATE INDEX idx_briefs_updated ON public.creative_briefs USING btree (updated_at DESC);
CREATE INDEX idx_campaigns_status ON public.campaigns USING btree (status);
CREATE INDEX idx_campaigns_brief ON public.campaigns USING btree (brief_id);
CREATE INDEX idx_rot_payment_request_business ON public.rot_payment_request USING btree (business_id, created_at DESC);
CREATE INDEX idx_invoice_rot_application_status ON public.invoice USING btree (business_id, rot_application_status);
CREATE INDEX idx_billing_event_business ON public.billing_event USING btree (business_id);
CREATE UNIQUE INDEX idx_billing_event_stripe_event_id ON public.billing_event USING btree (stripe_event_id) WHERE (stripe_event_id IS NOT NULL);
CREATE INDEX idx_product_categories_biz ON public.product_categories USING btree (business_id, parent_id);
CREATE UNIQUE INDEX idx_products_sku_unique ON public.products USING btree (business_id, lower(sku)) WHERE (sku IS NOT NULL);
CREATE INDEX idx_products_category ON public.products USING btree (category_id) WHERE (category_id IS NOT NULL);
CREATE INDEX idx_product_components_product ON public.product_components USING btree (product_id);
CREATE INDEX idx_quotes_created_by ON public.quotes USING btree (created_by) WHERE (created_by IS NOT NULL);
CREATE INDEX idx_customer_fortnox_number ON public.customer USING btree (business_id, fortnox_customer_number) WHERE (fortnox_customer_number IS NOT NULL);
CREATE INDEX idx_project_outcome_business_jobtype ON public.project_outcome USING btree (business_id, job_type);
CREATE INDEX idx_project_outcome_business_template ON public.project_outcome USING btree (business_id, template_id);
CREATE INDEX idx_service_agreement_type_business ON public.service_agreement_type USING btree (business_id, is_active);
CREATE INDEX idx_service_agreement_business_status_nextvisit ON public.service_agreement USING btree (business_id, status, next_visit_at);
CREATE INDEX idx_service_agreement_customer ON public.service_agreement USING btree (business_id, customer_id);
CREATE INDEX idx_booking_agreement ON public.booking USING btree (agreement_id) WHERE (agreement_id IS NOT NULL);
CREATE INDEX idx_invoice_booking ON public.invoice USING btree (booking_id) WHERE (booking_id IS NOT NULL);
CREATE INDEX idx_business_preferences_business ON public.business_preferences USING btree (business_id);
CREATE INDEX idx_time_checkins_business_user ON public.time_checkins USING btree (business_user_id);
CREATE INDEX idx_pending_approvals_routing ON public.pending_approvals USING btree (business_id, routing_role) WHERE (status = 'pending'::text);
CREATE INDEX idx_employee_certificate_business_user ON public.employee_certificate USING btree (business_id, business_user_id);
CREATE INDEX idx_employee_certificate_valid_until ON public.employee_certificate USING btree (valid_until);
CREATE INDEX idx_customer_phone_optout ON public.customer USING btree (business_id, phone_number) WHERE (phone_number IS NOT NULL);
CREATE INDEX idx_reservation_texts_business ON public.reservation_texts USING btree (business_id, is_active);
CREATE UNIQUE INDEX idx_reservation_texts_system_key ON public.reservation_texts USING btree (business_id, system_key) WHERE (system_key IS NOT NULL);
CREATE INDEX idx_reservation_triggers_business ON public.reservation_triggers USING btree (business_id);
CREATE INDEX idx_reservation_triggers_reservation ON public.reservation_triggers USING btree (reservation_id);
CREATE UNIQUE INDEX quotes_business_year_number_unique ON public.quotes USING btree (business_id, EXTRACT(year FROM (created_at AT TIME ZONE 'UTC'::text)), quote_number) WHERE (quote_number IS NOT NULL);
CREATE INDEX idx_demo_reset_audit_business_started ON public.demo_reset_audit USING btree (business_id, started_at DESC);
CREATE INDEX idx_cost_event_business_created ON public.cost_event USING btree (business_id, created_at DESC);
CREATE INDEX idx_cost_event_business_resource_created ON public.cost_event USING btree (business_id, resource, created_at DESC);
CREATE INDEX idx_call_recording_business_source ON public.call_recording USING btree (business_id, source, created_at DESC);
CREATE UNIQUE INDEX project_one_per_quote ON public.project USING btree (business_id, quote_id) WHERE (quote_id IS NOT NULL);
CREATE INDEX idx_email_inbound_route_business ON public.email_inbound_route USING btree (business_id);
CREATE INDEX idx_leads_referral_customer ON public.leads USING btree (business_id, referral_customer_id) WHERE (referral_customer_id IS NOT NULL);
CREATE INDEX idx_deal_referral_customer ON public.deal USING btree (business_id, referral_customer_id) WHERE (referral_customer_id IS NOT NULL);
CREATE INDEX idx_calendar_watches_connection_id ON public.calendar_watches USING btree (calendar_connection_id);
CREATE INDEX landing_events_event_created_idx ON public.landing_events USING btree (event, created_at);
CREATE INDEX landing_events_session_idx ON public.landing_events USING btree (session_id);
CREATE INDEX idx_pcl_partner_period ON public.partner_commission_ledger USING btree (partner_id, period);
CREATE INDEX idx_pcl_partner_status ON public.partner_commission_ledger USING btree (partner_id, status);
CREATE INDEX idx_partner_followups_partner ON public.partner_followups USING btree (partner_id);
CREATE INDEX idx_billing_event_type_created ON public.billing_event USING btree (event_type, created_at);
CREATE INDEX idx_schedule_entry_customer ON public.schedule_entry USING btree (business_id, customer_id) WHERE (customer_id IS NOT NULL);
CREATE INDEX idx_meeting_job_business_status ON public.meeting_job USING btree (business_id, status);
CREATE INDEX idx_meeting_job_status ON public.meeting_job USING btree (status) WHERE (status = ANY (ARRAY['finalized'::text, 'processing'::text, 'capturing'::text]));
CREATE INDEX idx_meeting_segment_job ON public.meeting_segment USING btree (job_id, seq);
CREATE INDEX idx_booking_meeting_reminder ON public.booking USING btree (business_id, scheduled_start) WHERE (meeting_reminder_pushed_at IS NULL);
CREATE INDEX idx_project_lesson_business_job_type ON public.project_lesson USING btree (business_id, job_type);
CREATE INDEX idx_customer_fact_business_customer ON public.customer_fact USING btree (business_id, customer_id);
CREATE INDEX idx_project_lesson_business_created ON public.project_lesson USING btree (business_id, created_at DESC);
CREATE UNIQUE INDEX idx_nba_business_date ON public.next_best_action USING btree (business_id, computed_date);
CREATE INDEX idx_nba_top_approval ON public.next_best_action USING btree (top_approval_id);
CREATE INDEX idx_fuel_ledger_business_created ON public.fuel_ledger USING btree (business_id, created_at DESC);
CREATE INDEX idx_fuel_ledger_stripe_session ON public.fuel_ledger USING btree (stripe_checkout_session_id);
CREATE UNIQUE INDEX project_quote_id_unique ON public.project USING btree (quote_id) WHERE (quote_id IS NOT NULL);
CREATE INDEX idx_project_outcome_quality_jobtype ON public.project_outcome USING btree (business_id, job_type, calculation_version) WHERE ((time_learning_eligible = true) OR (financial_learning_eligible = true));
CREATE INDEX idx_project_outcome_quality_template ON public.project_outcome USING btree (business_id, template_id, calculation_version) WHERE ((time_learning_eligible = true) OR (financial_learning_eligible = true));
CREATE INDEX idx_business_twin_forecast_project_status ON public.business_twin_forecast USING btree (business_id, project_id, status);
CREATE INDEX idx_benchmark_consent_audit_business_created ON public.benchmark_consent_audit USING btree (business_id, created_at DESC);
CREATE INDEX idx_business_knowledge_business_type_jobtype ON public.business_knowledge USING btree (business_id, knowledge_type, job_type);
CREATE INDEX idx_project_checklist_project ON public.project_checklist USING btree (project_id);
CREATE UNIQUE INDEX idx_mission_one_active ON public.mission USING btree (business_id) WHERE (status = 'active'::text);
CREATE INDEX idx_mission_business_status ON public.mission USING btree (business_id, status);
CREATE INDEX idx_customer_fact_open_promises ON public.customer_fact USING btree (business_id, due_at) WHERE (promise_status = 'open'::text);
CREATE INDEX idx_invmf_business_status ON public.invoice_evidence_manifest USING btree (business_id, status);
CREATE INDEX idx_invmf_incomplete ON public.invoice_evidence_manifest USING btree (prepared_at) WHERE (status = ANY (ARRAY['prepared'::text, 'incomplete'::text]));
CREATE INDEX idx_agent_memories_active ON public.agent_memories USING btree (business_id, agent_id, importance_score DESC) WHERE ((superseded_by IS NULL) AND (confirmed_at IS NOT NULL));
CREATE INDEX idx_mandate_business_active ON public.mission_mandate USING btree (business_id) WHERE (status = 'active'::text);
CREATE UNIQUE INDEX idx_sms_conversation_provider_dedup ON public.sms_conversation USING btree (business_id, provider_message_id) WHERE (provider_message_id IS NOT NULL);
CREATE INDEX idx_jobbpass_business ON public.jobbpass USING btree (business_id);
CREATE INDEX idx_operating_experiment_business_status ON public.operating_experiment USING btree (business_id, status);
CREATE INDEX idx_operating_experiment_business_jobtype ON public.operating_experiment USING btree (business_id, job_type);
CREATE INDEX idx_project_material_supplier_invoice ON public.project_material USING btree (supplier_invoice_id);
CREATE INDEX idx_supplier_invoices_subcontractor ON public.supplier_invoices USING btree (subcontractor_id);
CREATE INDEX idx_supplier_invoices_fortnox_number ON public.supplier_invoices USING btree (business_id, fortnox_supplier_invoice_number) WHERE (fortnox_supplier_invoice_number IS NOT NULL);
CREATE INDEX idx_support_ticket_status ON public.support_ticket USING btree (status, escalated_at);
CREATE INDEX idx_support_ticket_business ON public.support_ticket USING btree (business_id);
CREATE INDEX idx_push_tokens_user_id ON public.push_tokens USING btree (user_id);
CREATE INDEX idx_karin_custom_event_business_date ON public.karin_custom_event USING btree (business_id, event_date);
CREATE UNIQUE INDEX gtm_account_org_number_unique ON public.gtm_account USING btree (org_number) WHERE (org_number IS NOT NULL);
CREATE INDEX gtm_account_queue ON public.gtm_account USING btree (status, next_action_at, fit_score DESC);
CREATE INDEX gtm_account_owner ON public.gtm_account USING btree (owner_user_id, status, next_action_at);
CREATE INDEX gtm_account_retention_review ON public.gtm_account USING btree (retention_review_at, status);
CREATE INDEX gtm_account_company_name ON public.gtm_account USING btree (company_name);
CREATE INDEX gtm_activity_account ON public.gtm_activity USING btree (account_id, happened_at DESC);
CREATE INDEX gtm_activity_admin ON public.gtm_activity USING btree (admin_user_id, happened_at DESC);
CREATE INDEX gtm_suppression_org_number ON public.gtm_suppression USING btree (org_number);
CREATE INDEX gtm_suppression_email ON public.gtm_suppression USING btree (lower(email));
CREATE INDEX gtm_suppression_phone ON public.gtm_suppression USING btree (phone);
CREATE INDEX idx_invoice_business_customer_paid ON public.invoice USING btree (business_id) WHERE (status = 'customer_paid'::text);
CREATE INDEX idx_project_business_fortnox_unsynced ON public.project USING btree (business_id, created_at) WHERE (fortnox_project_number IS NULL);
CREATE INDEX idx_customer_document_deal ON public.customer_document USING btree (deal_id) WHERE (deal_id IS NOT NULL);
CREATE UNIQUE INDEX uq_installation_material ON public.installation USING btree (material_id) WHERE (material_id IS NOT NULL);
CREATE INDEX idx_installation_business_project ON public.installation USING btree (business_id, project_id);
CREATE INDEX idx_installation_business_customer ON public.installation USING btree (business_id, customer_id);
CREATE INDEX idx_warranty_business_project ON public.warranty USING btree (business_id, project_id);
CREATE INDEX idx_warranty_business_installation ON public.warranty USING btree (business_id, installation_id);
CREATE UNIQUE INDEX uq_project_number_per_business ON public.project USING btree (business_id, project_number) WHERE (project_number IS NOT NULL);
CREATE INDEX idx_project_tip_dismissal_business_project ON public.project_tip_dismissal USING btree (business_id, project_id);
CREATE INDEX idx_lead_number ON public.leads USING btree (business_id, lead_number);
CREATE UNIQUE INDEX products_business_name_unit_key ON public.products USING btree (business_id, lower(TRIM(BOTH FROM name)), unit);
CREATE INDEX quote_templates_job_type_idx ON public.quote_templates USING btree (business_id, job_type_slug) WHERE (job_type_slug IS NOT NULL);
CREATE INDEX push_dispatch_log_dedupe_idx ON public.push_dispatch_log USING btree (business_id, dedupe_key, sent_at DESC);
CREATE INDEX idx_call_recording_elks_id ON public.call_recording USING btree (elks_recording_id);
CREATE INDEX idx_call_recording_deal ON public.call_recording USING btree (deal_id) WHERE (deal_id IS NOT NULL);
CREATE UNIQUE INDEX partner_commission_ledger_source_key_unique ON public.partner_commission_ledger USING btree (partner_id, source_key);
CREATE INDEX partner_commission_ledger_adjusts_idx ON public.partner_commission_ledger USING btree (adjusts_ledger_id) WHERE (adjusts_ledger_id IS NOT NULL);
CREATE UNIQUE INDEX partner_payout_batch_invoice_number_unique ON public.partner_payout_batch USING btree (invoice_number) WHERE (invoice_number IS NOT NULL);
CREATE UNIQUE INDEX push_held_open_dedupe_idx ON public.push_held USING btree (business_id, dedupe_key) WHERE (released_at IS NULL);
CREATE INDEX push_held_open_idx ON public.push_held USING btree (created_at) WHERE (released_at IS NULL);
CREATE INDEX idx_push_subscriptions_business ON public.push_subscriptions USING btree (business_id);
CREATE INDEX idx_push_subscriptions_business_user ON public.push_subscriptions USING btree (business_id, user_id);
CREATE INDEX idx_project_document_change ON public.project_document USING btree (business_id, change_id) WHERE (change_id IS NOT NULL);
CREATE INDEX idx_project_log_order_date ON public.project_log USING btree (order_id, date DESC);
CREATE INDEX idx_project_log_ata ON public.project_log USING btree (ata_change_id) WHERE (ata_change_id IS NOT NULL);
CREATE INDEX idx_project_log_revision_log ON public.project_log_revision USING btree (business_id, log_id, changed_at DESC);
CREATE INDEX idx_agent_memories_customer ON public.agent_memories USING btree (business_id, customer_id) WHERE (customer_id IS NOT NULL);
CREATE INDEX idx_agent_memories_content_tsv ON public.agent_memories USING gin (content_tsv);
CREATE UNIQUE INDEX raddningsarende_oppet_idx ON public.raddningsarende USING btree (business_id, signal) WHERE (status = ANY (ARRAY['oppet'::text, 'pagaende'::text]));
CREATE INDEX raddningsarende_status_idx ON public.raddningsarende USING btree (status, last_seen_at DESC);
CREATE INDEX lanseringsbevis_station_idx ON public.lanseringsbevis USING btree (station, proven_at DESC);
CREATE UNIQUE INDEX referrals_one_partner_per_business ON public.referrals USING btree (referred_business_id) WHERE (referrer_type = 'partner'::text);
CREATE INDEX partner_attribution_decision_business ON public.partner_attribution_decision USING btree (business_id, created_at DESC);
CREATE INDEX partner_attribution_decision_partner ON public.partner_attribution_decision USING btree (partner_id, created_at DESC) WHERE (partner_id IS NOT NULL);
CREATE INDEX idx_deal_business_created ON public.deal USING btree (business_id, created_at);
CREATE INDEX idx_deal_business_stage ON public.deal USING btree (business_id, stage_id);
CREATE INDEX idx_business_config_deleted ON public.business_config USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);
CREATE INDEX customer_preparation_customer ON public.customer_preparation USING btree (business_id, customer_id, created_at DESC);
CREATE INDEX idx_rate_limit_reset ON public.rate_limit_bucket USING btree (reset_at);
CREATE UNIQUE INDEX invoice_en_slutfaktura_per_projekt ON public.invoice USING btree (business_id, project_id) WHERE ((invoice_type = 'final'::text) AND (project_id IS NOT NULL) AND (status <> ALL (ARRAY['cancelled'::text, 'credited'::text])));
CREATE INDEX idx_portal_review_customer ON public.portal_review USING btree (business_id, customer_id, created_at DESC);
