import { CARD_KIND } from './card-kind'

/** Explicit policy axis: internal gates stay open even though they need a decision. */
export const EXPIRY_DAYS = {
  agent_observation: null,
  send_sms: 7,
  send_email: 7,
  send_quote: 7,
  send_invoice: 7,
  send_matte_customer_reply: 7,
  quote_nudge: 7,
  confirm_payment: 7,
  create_booking: 7,
  create_quote_draft: 7,
  create_ata_draft: 7,
  create_invoice_from_report: 7,
  autopilot_package: 7,
  autonomy_offer: 14,
  review_request: 7,
  scheduled_review_request: 7,
  yearly_followup: 7,
  proactive_care: 7,
  warranty_followup: 7,
  seasonal_campaign: 7,
  customer_reactivation: 7,
  customer_message: 7,
  customer_quote_question: 7,
  quote_request: 7,
  quote_addition: 7,
  propose_booking_times: 7,
  propose_site_visit: 7,
  reschedule_request: 7,
  new_booking_request: 7,
  dispatch_suggestion: null,
  publish_microsite: 7,
  invoice_reminder: 7,
  automation: 7,
  price_adjustment: 7,
  fakturera_projekt: 7,
  project_debrief: null,
  playbook_pattern_confirmation: 7,
  playbook_kickoff_suggestion: 7,
  operating_experiment_proposal: 7,
  operating_experiment_readout: 7,
  missad_intakt: 7,
  manual_project_create: null,
  jobbpass_proposal: 7,
  installation_register: null,
  review_auto_invoice: null,
  four_eyes_quote: null,
  four_eyes_project_close: null,
  deal_flow_site_visit: 7,
  lead_review: null,
  time_attestation: null,
  tidrapport_forslag: null,
  checklist_forslag: null,
  egenkontroll_foto: null,
  egenkontroll_avvikelse: null,
  job_report: null,
  karin_deadline: null,
  cert_expiry_reminder: 7,
  low_stock_alert: 7,
  agent_insight: null,
  monthly_review: null,
  monday_brief: null,
  quote_signed: null,
  ata_signed_notification: null,
  ata_declined_notification: null,
  profitability_warning: null,
  meeting_summary: null,
  meeting_followup: 7,
  project_log_note: 7,
  customer_fact: 7,
  agent_memory_confirmation: 7,
  autonomy_revoked: null,
  team_intro: null,
  expectation_drift_signal: null,
  promise_deadline_signal: null,
  mandate_paused_signal: null,
  external_delivery_failure_signal: null,
  payment_failed_signal: null,
  kort_gar_ut: null,
} as const satisfies Record<keyof typeof CARD_KIND, 7 | 14 | null>

/** Unknown types get no implicit seven-day deadline; the contract test catches them. */
export const expiryFor = (type: string): 7 | 14 | null =>
  Object.prototype.hasOwnProperty.call(EXPIRY_DAYS, type)
    ? EXPIRY_DAYS[type as keyof typeof EXPIRY_DAYS]
    : null
export function expiryAt(type: string, createdAt = new Date()): string | null {
  const days = expiryFor(type)
  return days === null
    ? null
    : new Date(createdAt.getTime() + days * 86400000).toISOString()
}
