const assert = require('node:assert/strict')
const { randomUUID } = require('node:crypto')
const { harness } = require('./harness.cjs')
async function main() {
 const h = await harness()
 const admin = 'https://revenue.test/api/admin/revenue/partner-leads'
 const portal = 'https://revenue.test/api/partners/leads'
 let checks = 0
 async function post(url, input, status=200) {
   const res = await h.request('POST',url,{ request_id: randomUUID(), ...input })
   const body = await res.json()
   assert.equal(res.status,status,JSON.stringify(body)); checks++
   return body
 }
 const get = async url => (await h.request('GET',url)).json()
 try {
  const p1 = { id: randomUUID(), name: 'Partner Ett', status:'active', agreement_version:'1.0' }
  const p2 = { ...p1, id:randomUUID(), name:'Partner Två' }
  for (const p of [p1,p2]) await h.db.query('insert into partners(id,name,status,agreement_version) values($1,$2,$3,$4)',Object.values(p))
  const { account_id } = await post('https://revenue.test/api/admin/revenue',{type:'create',company_name:'Delbar El AB',org_number:'5565551234'})
  const { id: contact_id } = await post('https://revenue.test/api/admin/revenue',{type:'contact',account_id,name:'Kundkontakt',email:'customer@example.test',contact_basis:'inbound'})
  await h.db.query("update revenue_accounts set notes='HEMLIG INTERN ANTECKNING',why_now='HEMLIG RESEARCH',icp_score=25 where id=$1",[account_id])
  const input = {type:'assign',account_id,partner_id:p1.id,contact_id,brief:'Kunden vill prata om enklare offertarbete.',version:0,request_id:randomUUID()}
  h.ctx.manager=false
  assert.equal((await h.request('GET',admin+'?account_id='+account_id)).status,403)
  await post(admin,input,403)
  h.ctx.manager=true
  const first = await post(admin,input)
  const csrf = await h.request('POST',admin,{ ...input, request_id:randomUUID() }, { origin:'https://attacker.example' })
  assert.equal(csrf.status,400)
  await post(admin,input)
  await post(admin,{...input,request_id:randomUUID(),version:1},409)
  assert.equal((await h.db.query('select count(*)::integer n from revenue_partner_leads')).rows[0].n,1)
  h.setPartner(p1)
  let inbox=await get(portal)
  assert.equal(inbox.total,1)
  assert.equal(inbox.leads[0].snapshot.contact_email,'customer@example.test')
  const raw=JSON.stringify(inbox)
  for (const forbidden of ['HEMLIG','icp_score','assigned_by','account_id','partner_id']) assert(!raw.includes(forbidden))
  h.setPartner(p2)
  assert.equal((await get(portal)).total,0)
  await post(portal,{lead_id:first.lead_id,version:0,status:'accepted'},403)
  h.setPartner(p1)
  const partnerCsrf = await h.request('POST',portal,{ lead_id:first.lead_id,version:0,status:'accepted',request_id:randomUUID() }, { origin:'https://attacker.example' })
  assert.equal(partnerCsrf.status,400)
  await post(portal,{lead_id:first.lead_id,version:0,status:'won',feedback:'För tidigt'},400)
  const accept={lead_id:first.lead_id,version:0,status:'accepted',request_id:randomUUID()}
  await post(portal,accept)
  await post(portal,accept)
  await post(portal,{lead_id:first.lead_id,version:0,status:'contacted'},409)
  await post(portal,{lead_id:first.lead_id,version:1,status:'contacted',feedback:'Pratade med ägaren.',next_action:'Boka genomgång',next_action_at:'2026-10-01T09:00:00+02:00'})
  const history=await get(admin+'?account_id='+account_id)
  assert.equal(history.leads[0].feedback,'Pratade med ägaren.')
  assert.equal(Date.parse(history.leads[0].next_action_at),Date.parse('2026-10-01T07:00:00Z'))
  await post(admin,{type:'revoke',lead_id:first.lead_id,version:1},409)
  await post(admin,{type:'revoke',lead_id:first.lead_id,version:2})
  assert.equal((await get(portal)).total,0)
  await post(portal,{lead_id:first.lead_id,version:3,status:'contacted'},409)
  await post(portal,accept,409)
  const second=await post(admin,{...input,request_id:randomUUID(),partner_id:p2.id,version:1})
  assert.equal((await get(portal)).total,0)
  h.setPartner(p2)
  await post(portal,{lead_id:second.lead_id,version:0,status:'declined'},400)
  await post(portal,{lead_id:second.lead_id,version:0,status:'declined',feedback:'Utanför vårt område.'})
  assert.equal((await get(portal)).total,0)
  const third=await post(admin,{...input,request_id:randomUUID(),version:2})
  h.setPartner(p1)
  await h.db.query("insert into gtm_suppression(email) values('customer@example.test')")
  assert.equal((await get(portal)).total,0)
  await post(portal,{lead_id:third.lead_id,version:0,status:'accepted'},409)
  await h.db.exec('delete from gtm_suppression')
  await h.db.query("update revenue_accounts set status='won' where id=$1",[account_id])
  assert.equal((await get(portal)).total,0)
  await post(portal,{lead_id:third.lead_id,version:0,status:'accepted'},409)
  await h.db.query("update revenue_accounts set status='identified' where id=$1",[account_id])
  await h.db.query("update partners set status='suspended' where id=$1",[p1.id])
  assert.equal((await get(portal)).total,0)
  await post(portal,{lead_id:third.lead_id,version:0,status:'accepted'},403)
  await h.db.query("update partners set status='active' where id=$1",[p1.id])
  await h.db.query("update partners set agreement_version=null where id=$1",[p1.id])
  await post(portal,{lead_id:third.lead_id,version:0,status:'accepted'},403)
  await h.db.query("update partners set agreement_version='1.0' where id=$1",[p1.id])
  await post(portal,{lead_id:third.lead_id,version:0,status:'accepted'})
  await post(portal,{lead_id:third.lead_id,version:1,status:'won',feedback:'Partnern rapporterar avtal.'})
  assert.equal((await h.db.query('select status from revenue_accounts where id=$1',[account_id])).rows[0].status,'identified')
  assert.equal((await h.db.query('select count(*)::integer n from revenue_partner_lead_events where lead_id=$1',[third.lead_id])).rows[0].n,3)
  h.setPartner(null)
  assert.equal((await h.request('GET',portal)).status,401)
  const privileges=(await h.db.query("select has_table_privilege('authenticated','revenue_partner_leads','SELECT') readable, has_function_privilege('anon','revenue_partner_lead_command(uuid,boolean,uuid,uuid,text,jsonb,text)','EXECUTE') executable")).rows[0]
  assert.deepEqual(privileges,{readable:false,executable:false})
  const {account_id: sequencedId}=await post('https://revenue.test/api/admin/revenue',{type:'create',company_name:'Sekvens AB'})
  const {id: sequenceContact}=await post('https://revenue.test/api/admin/revenue',{type:'contact',account_id:sequencedId,name:'Sekvenskontakt',email:'seq@example.test',phone:'0701112233',contact_basis:'inbound'})
  await post('https://revenue.test/api/admin/revenue',{type:'sequence_start',account_id:sequencedId,version:0,contact_id:sequenceContact,due_at:new Date().toISOString()})
  await post(admin,{type:'assign',account_id:sequencedId,version:1,contact_id:sequenceContact,partner_id:p1.id,brief:'Partnern tar över.'})
  assert.equal((await h.db.query('select status from revenue_sequences where account_id=$1',[sequencedId])).rows[0].status,'stopped')
  await post('https://revenue.test/api/admin/revenue',{type:'sequence_start',account_id:sequencedId,version:2,contact_id:sequenceContact,due_at:new Date().toISOString()},409)
  // Read pages include all authorized assignments, not another partner's portfolio.
  await h.db.query("with a as (insert into revenue_accounts(company_name) select 'Lead '||n from generate_series(1,51) n returning id,company_name) insert into revenue_partner_leads(account_id,partner_id,snapshot,brief,assigned_by) select id,$1,jsonb_build_object('company_name',company_name),'Fixture',$2 from a",[p1.id,h.ctx.userId])
  h.setPartner(p1)
  assert.equal((await get(portal)).leads.length,50)
  assert.equal((await get(portal+'?offset=50')).leads.length,3)
  assert.equal((await get(portal)).total,53)
  console.log(`PASS ${checks} partner lead handler checks: assignment, acceptance, refusal, revoke, ownership, snapshots, suppression, retry and audit`)
 } finally { await h.db.close() }
}
main().catch(e=>{console.error(e);process.exitCode=1})
